apiVersion: v1
kind: Service
metadata:
  name: simple-service
  labels:
    app.kubernetes.io/name: "simple-java-service"  
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"  
spec:
  type: ClusterIP
  selector:
    app: simple-java-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080